#!/usr/bin/env python3
"""
make_bundle.py -- pack files and folders into ONE self-verifying Python file.

    python make_bundle.py --out pheauxwas_bundle.py ^
        --file pheauxWAS.py ^
        --dir pyPheWAS=pyPheWAS ^
        --exclude-ext png,jpg,jpeg,gif,bmp,ico,svg,webp,tif,tiff,gz ^
        --check-deps numpy,pandas,scipy,statsmodels,matplotlib,tqdm ^
        --pythonpath pyPheWAS ^
        --note "pheauxWAS 1.1.0 + pyPheWAS commit 2a8fff1"

The generated bundle needs only the Python standard library. On the target:

    python phewas_bundle.py info                     # shows the PACK_ID
    python phewas_bundle.py verify --expect <PACK_ID>
    python phewas_bundle.py unpack <folder> --expect <PACK_ID>

PACK_ID is the SHA-256 of the bundle's manifest, which itself lists the SHA-256
of every file and of the compressed payload, so any corruption of any byte is
detected before anything is written to disk.
"""
import argparse
import base64
import hashlib
import json
import os
import sys
import time
import zlib

SKIP_DIRS = {".git", "__pycache__", ".ipynb_checkpoints", ".pytest_cache",
             ".mypy_cache", ".venv", "venv", "node_modules"}

TEMPLATE = r'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Self-verifying bundle generated by make_bundle.py (standard library only).

    python {name} info                       show PACK_ID and contents summary
    python {name} list                       list every file with its SHA-256
    python {name} verify [--expect PACK_ID]  check integrity, write nothing
    python {name} unpack [DEST] [--expect PACK_ID] [--force]
                                             verify, then extract to DEST
    python {name} check [DEST]               after unpacking: test whether the
                                             Python packages the bundled code
                                             needs are importable here

PACK_ID = SHA-256 of the manifest (every file's path, size and SHA-256, plus
the SHA-256 of the compressed payload). Compare it with the PACK_ID you noted
before the transfer. Line-ending changes during transfer do not matter: the
payload is whitespace-insensitive and every file is checked byte-for-byte.
"""
import argparse, base64, hashlib, importlib, json, os, sys, zlib

PACK_ID = "{pack_id}"
MANIFEST_JSON = r"""{manifest}"""
PAYLOAD = """
{payload}
"""



def _die(msg):
    sys.stderr.write("ERROR: " + msg + "\n")
    sys.exit(1)


def _manifest_id(text):
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()


def load(expect=None):
    """Verify everything in memory; return (manifest, {{path: bytes}})."""
    got = _manifest_id(MANIFEST_JSON)
    if got != PACK_ID:
        _die("manifest hash %s does not match embedded PACK_ID %s: the bundle "
             "is corrupted" % (got, PACK_ID))
    if expect and expect.strip().lower() != PACK_ID:
        _die("PACK_ID is %s but you expected %s: this is not the bundle you "
             "think it is" % (PACK_ID, expect))
    man = json.loads(MANIFEST_JSON)
    try:
        comp = base64.b64decode("".join(PAYLOAD.split()), validate=True)
    except Exception as e:
        _die("payload is not valid base64 (%s): the bundle is corrupted" % e)
    if hashlib.sha256(comp).hexdigest() != man["payload_sha256"]:
        _die("payload SHA-256 mismatch: the bundle is corrupted")
    blob = zlib.decompress(comp)
    if len(blob) != man["total_bytes"]:
        _die("payload size mismatch: the bundle is corrupted")
    files = {{}}
    for f in man["files"]:
        data = blob[f["offset"]:f["offset"] + f["size"]]
        if hashlib.sha256(data).hexdigest() != f["sha256"]:
            _die("SHA-256 mismatch for %s" % f["path"])
        files[f["path"]] = data
    return man, files


def _safe_target(dest, rel):
    parts = rel.split("/")
    if rel.startswith("/") or ":" in parts[0] or any(p in ("", "..") for p in parts):
        _die("unsafe path in bundle: %r" % rel)
    root = os.path.abspath(dest)
    target = os.path.abspath(os.path.join(root, *parts))
    if os.path.commonpath([root, target]) != root:
        _die("unsafe path in bundle: %r" % rel)
    return target


def cmd_info(a):
    man, _ = load(a.expect)
    print("PACK_ID     : %s" % PACK_ID)
    print("created     : %s" % man["created"])
    print("note        : %s" % man.get("note", ""))
    print("files       : %d (%d bytes unpacked)" % (len(man["files"]), man["total_bytes"]))
    tops = sorted(set(f["path"].split("/")[0] for f in man["files"]))
    print("top level   : %s" % ", ".join(tops))
    if man.get("excluded"):
        print("excluded    : %d files (%s)" % (len(man["excluded"]),
              ", ".join(sorted(set(os.path.splitext(p)[1] for p in man["excluded"])))))
    print("integrity   : OK")


def cmd_list(a):
    man, _ = load(a.expect)
    for f in man["files"]:
        print("%s  %10d  %s" % (f["sha256"], f["size"], f["path"]))
    print("PACK_ID %s  (%d files, integrity OK)" % (PACK_ID, len(man["files"])))


def cmd_verify(a):
    man, _ = load(a.expect)
    print("OK: all %d files verified. PACK_ID %s" % (len(man["files"]), PACK_ID))


def cmd_unpack(a):
    man, files = load(a.expect)
    dest = a.dest
    targets = [(_safe_target(dest, f["path"]), f) for f in man["files"]]
    clash = [t for t, _ in targets if os.path.exists(t)]
    if clash and not a.force:
        _die("%d files already exist in %s (e.g. %s). Use --force to overwrite "
             "or choose another folder." % (len(clash), os.path.abspath(dest), clash[0]))
    for t, f in targets:
        os.makedirs(os.path.dirname(t), exist_ok=True)
        with open(t, "wb") as fh:
            fh.write(files[f["path"]])
    bad = []
    for t, f in targets:          # re-read from disk and check again
        h = hashlib.sha256()
        with open(t, "rb") as fh:
            h.update(fh.read())
        if h.hexdigest() != f["sha256"]:
            bad.append(t)
    if bad:
        _die("%d files failed verification after writing, e.g. %s" % (len(bad), bad[0]))
    with open(os.path.join(dest, "BUNDLE_MANIFEST.json"), "w", encoding="utf-8") as fh:
        fh.write(MANIFEST_JSON.strip() + "\n")
    print("Unpacked and verified %d files into %s" % (len(targets), os.path.abspath(dest)))
    print("PACK_ID %s" % PACK_ID)


def cmd_check(a):
    man = json.loads(MANIFEST_JSON)
    deps = man.get("check_deps", [])
    print("Python %s" % sys.version.split()[0])
    if not deps:
        print("  (this bundle lists no dependencies to check)")
    missing = []
    for mod in deps:
        try:
            m = importlib.import_module(mod)
            print("  ok       %-24s %s" % (mod, getattr(m, "__version__", "")))
        except Exception as e:
            missing.append(mod)
            print("  MISSING  %-24s (%s)" % (mod, type(e).__name__))
    if missing:
        print("\n%d of %d listed dependencies are missing: %s"
              % (len(missing), len(deps), ", ".join(missing)))
    elif deps:
        print("\nAll %d listed dependencies found." % len(deps))
    paths = [os.path.join(os.path.abspath(a.dest), *p.split("/"))
             for p in man.get("pythonpath", [])]
    if paths:
        print("\nTo use the bundled Python code without installing it, put these on")
        print("PYTHONPATH (separate several with ';' on Windows, ':' on Mac/Linux):")
        for p in paths:
            print("  " + p)
        print("Windows cmd:  set PYTHONPATH=%s" % ";".join(paths))
        print("Mac/Linux:    export PYTHONPATH=%s" % ":".join(paths))


def main():
    ap = argparse.ArgumentParser(description="Self-verifying bundle. PACK_ID " + PACK_ID)
    sub = ap.add_subparsers(dest="cmd")
    for name in ("info", "list", "verify"):
        p = sub.add_parser(name)
        p.add_argument("--expect", help="PACK_ID you expect; abort if different")
    p = sub.add_parser("unpack")
    p.add_argument("dest", nargs="?", default=".", help="destination folder")
    p.add_argument("--expect", help="PACK_ID you expect; abort if different")
    p.add_argument("--force", action="store_true", help="overwrite existing files")
    p = sub.add_parser("check")
    p.add_argument("dest", nargs="?", default=".", help="folder you unpacked into")
    a = ap.parse_args()
    if not a.cmd:
        ap.print_help()
        print("\nPACK_ID %s" % PACK_ID)
        return
    {{"info": cmd_info, "list": cmd_list, "verify": cmd_verify,
     "unpack": cmd_unpack, "check": cmd_check}}[a.cmd](a)


if __name__ == "__main__":
    main()
'''


def collect(args):
    entries, excluded = [], []
    exts = {"." + e.strip().lower().lstrip(".") for e in args.exclude_ext.split(",") if e.strip()}
    skip_abs = {os.path.abspath(d) for d in args.exclude_dir}
    skip_files = {os.path.abspath(f) for f in args.exclude_file}
    out_abs = os.path.abspath(args.out)
    for f in args.file:
        entries.append((os.path.basename(f), f))
    for spec in args.dir:
        src, _, prefix = spec.partition("=")
        prefix = (prefix or os.path.basename(os.path.normpath(src))).strip("/\\")
        for root, dirs, fnames in os.walk(src):
            dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS
                             and os.path.abspath(os.path.join(root, d)) not in skip_abs)
            for fn in sorted(fnames):
                full = os.path.join(root, fn)
                if os.path.abspath(full) == out_abs:
                    continue            # never pack the bundle into itself
                rel = os.path.relpath(full, src).replace(os.sep, "/")
                arc = prefix + "/" + rel
                if (os.path.splitext(fn)[1].lower() in exts or fn.endswith(".pyc")
                        or os.path.abspath(full) in skip_files):
                    excluded.append(arc)
                    continue
                entries.append((arc, full))
    return entries, excluded


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True, help="bundle file to write (.py)")
    ap.add_argument("--file", action="append", default=[], help="single file to include")
    ap.add_argument("--dir", action="append", default=[],
                    help="folder to include, SRC or SRC=PREFIX")
    ap.add_argument("--exclude-ext", default="png,jpg,jpeg,gif,bmp,ico,svg,webp,tif,tiff")
    ap.add_argument("--exclude-dir", action="append", default=[],
                    help="folder to leave out, as a path (repeatable), e.g. --exclude-dir bundles")
    ap.add_argument("--exclude-file", action="append", default=[],
                    help="single file to leave out, as a path (repeatable), e.g. --exclude-file README.md")
    ap.add_argument("--note", default="")
    ap.add_argument("--check-deps", default="",
                    help="comma-separated modules that 'check' should try to import")
    ap.add_argument("--pythonpath", action="append", default=[],
                    help="bundle-relative folder that 'check' should suggest adding "
                         "to PYTHONPATH (repeatable)")
    args = ap.parse_args()

    entries, excluded = collect(args)
    seen = set()
    blob = bytearray()
    files = []
    for arc, full in entries:
        if arc in seen:
            sys.exit("duplicate path in bundle: " + arc)
        seen.add(arc)
        with open(full, "rb") as fh:
            data = fh.read()
        files.append({"path": arc, "size": len(data), "offset": len(blob),
                      "sha256": hashlib.sha256(data).hexdigest()})
        blob += data
    comp = zlib.compress(bytes(blob), 9)
    manifest = {"format": "pybundle-1", "created": time.strftime("%Y-%m-%d %H:%M:%S %z"),
                "note": args.note, "total_bytes": len(blob),
                "payload_sha256": hashlib.sha256(comp).hexdigest(),
                "files": files, "excluded": excluded,
                "check_deps": [d.strip() for d in args.check_deps.split(",") if d.strip()],
                "pythonpath": [p.strip("/\\").replace("\\", "/") for p in args.pythonpath]}
    man_text = json.dumps(manifest, indent=1, sort_keys=True)
    assert '"""' not in man_text
    pack_id = hashlib.sha256(man_text.strip().encode("utf-8")).hexdigest()
    b64 = base64.b64encode(comp).decode("ascii")
    payload = "\n".join(b64[i:i + 100] for i in range(0, len(b64), 100))
    out = TEMPLATE.format(name=os.path.basename(args.out), pack_id=pack_id,
                          manifest=man_text, payload=payload)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(out)
    print("wrote %s: %d files, %d bytes unpacked, %d bytes bundle"
          % (args.out, len(files), len(blob), os.path.getsize(args.out)))
    print("excluded %d files" % len(excluded))
    print("PACK_ID %s" % pack_id)


if __name__ == "__main__":
    main()
